# Generated by Django 5.0.6 on 2024-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpro', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
